cp /home/kin/t2-integradora/$1 /home/kin/t2-integradora/blocks-world/$1
cp /home/kin/t2-integradora/$1 /home/kin/t2-integradora/blocks-world-noisy/$1
cp /home/kin/t2-integradora/$1 /home/kin/t2-integradora/campus/$1
cp /home/kin/t2-integradora/$1 /home/kin/t2-integradora/campus-noisy/$1
cp /home/kin/t2-integradora/$1 /home/kin/t2-integradora/depots/$1
cp /home/kin/t2-integradora/$1 /home/kin/t2-integradora/depots-noisy/$1
cp /home/kin/t2-integradora/$1 /home/kin/t2-integradora/driverlog/$1
cp /home/kin/t2-integradora/$1 /home/kin/t2-integradora/driverlog-noisy/$1
cp /home/kin/t2-integradora/$1 /home/kin/t2-integradora/dwr/$1
cp /home/kin/t2-integradora/$1 /home/kin/t2-integradora/dwr-noisy/$1
cp /home/kin/t2-integradora/$1 /home/kin/t2-integradora/easy-ipc-grid/$1
cp /home/kin/t2-integradora/$1 /home/kin/t2-integradora/easy-ipc-grid-noisy/$1
cp /home/kin/t2-integradora/$1 /home/kin/t2-integradora/ferry/$1
cp /home/kin/t2-integradora/$1 /home/kin/t2-integradora/ferry-noisy/$1
cp /home/kin/t2-integradora/$1 /home/kin/t2-integradora/intrusion-detection/$1
cp /home/kin/t2-integradora/$1 /home/kin/t2-integradora/intrusion-detection-noisy/$1
cp /home/kin/t2-integradora/$1 /home/kin/t2-integradora/kitchen/$1
cp /home/kin/t2-integradora/$1 /home/kin/t2-integradora/kitchen-noisy/$1
cp /home/kin/t2-integradora/$1 /home/kin/t2-integradora/logistics/$1
cp /home/kin/t2-integradora/$1 /home/kin/t2-integradora/logistics-noisy/$1
cp /home/kin/t2-integradora/$1 /home/kin/t2-integradora/miconic/$1
cp /home/kin/t2-integradora/$1 /home/kin/t2-integradora/miconic-noisy/$1
cp /home/kin/t2-integradora/$1 /home/kin/t2-integradora/rovers/$1
cp /home/kin/t2-integradora/$1 /home/kin/t2-integradora/rovers-noisy/$1
cp /home/kin/t2-integradora/$1 /home/kin/t2-integradora/satellite/$1
cp /home/kin/t2-integradora/$1 /home/kin/t2-integradora/satellite-noisy/$1
cp /home/kin/t2-integradora/$1 /home/kin/t2-integradora/sokoban/$1
cp /home/kin/t2-integradora/$1 /home/kin/t2-integradora/sokoban-noisy/$1
cp /home/kin/t2-integradora/$1 /home/kin/t2-integradora/zeno-travel/$1
cp /home/kin/t2-integradora/$1 /home/kin/t2-integradora/zeno-travel-noisy/$1
