cp /home/kin/tcc/$1 /home/kin/tcc/blocks-world/$1
cp /home/kin/tcc/$1 /home/kin/tcc/blocks-world-noisy/$1
cp /home/kin/tcc/$1 /home/kin/tcc/campus/$1
cp /home/kin/tcc/$1 /home/kin/tcc/campus-noisy/$1
cp /home/kin/tcc/$1 /home/kin/tcc/depots/$1
cp /home/kin/tcc/$1 /home/kin/tcc/depots-noisy/$1
cp /home/kin/tcc/$1 /home/kin/tcc/driverlog/$1
cp /home/kin/tcc/$1 /home/kin/tcc/driverlog-noisy/$1
cp /home/kin/tcc/$1 /home/kin/tcc/dwr/$1
cp /home/kin/tcc/$1 /home/kin/tcc/dwr-noisy/$1
cp /home/kin/tcc/$1 /home/kin/tcc/easy-ipc-grid/$1
cp /home/kin/tcc/$1 /home/kin/tcc/easy-ipc-grid-noisy/$1
cp /home/kin/tcc/$1 /home/kin/tcc/ferry/$1
cp /home/kin/tcc/$1 /home/kin/tcc/ferry-noisy/$1
cp /home/kin/tcc/$1 /home/kin/tcc/intrusion-detection/$1
cp /home/kin/tcc/$1 /home/kin/tcc/intrusion-detection-noisy/$1
cp /home/kin/tcc/$1 /home/kin/tcc/kitchen/$1
cp /home/kin/tcc/$1 /home/kin/tcc/kitchen-noisy/$1
cp /home/kin/tcc/$1 /home/kin/tcc/logistics/$1
cp /home/kin/tcc/$1 /home/kin/tcc/logistics-noisy/$1
cp /home/kin/tcc/$1 /home/kin/tcc/miconic/$1
cp /home/kin/tcc/$1 /home/kin/tcc/miconic-noisy/$1
cp /home/kin/tcc/$1 /home/kin/tcc/rovers/$1
cp /home/kin/tcc/$1 /home/kin/tcc/rovers-noisy/$1
cp /home/kin/tcc/$1 /home/kin/tcc/satellite/$1
cp /home/kin/tcc/$1 /home/kin/tcc/satellite-noisy/$1
cp /home/kin/tcc/$1 /home/kin/tcc/sokoban/$1
cp /home/kin/tcc/$1 /home/kin/tcc/sokoban-noisy/$1
cp /home/kin/tcc/$1 /home/kin/tcc/zeno-travel/$1
cp /home/kin/tcc/$1 /home/kin/tcc/zeno-travel-noisy/$1
