(define (problem pb7)
(:domain blocks)
(:objects D J H P B Q G E I M C F A O N L K - block)
(:INIT (CLEAR K) (CLEAR L) (CLEAR N) (ONTABLE O) (ONTABLE A) (ONTABLE F)
 (ON K C) (ON C M) (ON M I) (ON I E) (ON E G) (ON G Q) (ON Q B) (ON B P)
 (ON P H) (ON H J) (ON J O) (ON L D) (ON D A) (ON N F) (HANDEMPTY))
(:goal (and
(on l n)  (on n p)  (on p c)  (on c q)  (on q i)  (on i k)  (on k f)  (on f j)  (on j b)  (on b g)  (on g a)  (on a h)  (on h e)  (on e m)  (on m o)  (on o d)
))
)